"""Update Product model: replace initial_stock with stock, add updated_at

Revision ID: 50de79cbcacf
Revises: 2d050e6db4fc
Create Date: 2025-10-23 13:23:19.616369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50de79cbcacf'
down_revision: Union[str, Sequence[str], None] = '2d050e6db4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('products', 'initial_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('initial_stock', sa.INTEGER(), nullable=False))
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
